import json
import os
import tempfile
import unittest
from unittest.mock import patch

os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")

from PyQt5.QtCore import QCoreApplication

from config import ScraperConfig, domain_matches
from scraper import OperationCancelledError, download_images, is_artsy_domain
from gui import (
    ScraperThread,
    build_environment_status,
    format_environment_status_lines,
    is_same_or_child_path,
    normalize_package_name,
    parse_locked_requirements,
    sanitize_history_item_text,
    sanitize_history_url,
)


class DomainDetectionTests(unittest.TestCase):
    def test_domain_match_allows_exact_domain_and_subdomain_only(self) -> None:
        self.assertTrue(domain_matches("artsy.net", "artsy.net"))
        self.assertTrue(domain_matches("www.artsy.net", "artsy.net"))
        self.assertFalse(domain_matches("notartsy.net", "artsy.net"))
        self.assertFalse(domain_matches("really-artsy.net.example.com", "artsy.net"))

    def test_artsy_domain_detection_uses_boundary_match(self) -> None:
        self.assertTrue(is_artsy_domain("artsy.net"))
        self.assertTrue(is_artsy_domain("www.artsy.net"))
        self.assertFalse(is_artsy_domain("notartsy.net"))


class PathSafetyTests(unittest.TestCase):
    def test_same_or_child_path_requires_real_path_boundary(self) -> None:
        self.assertTrue(is_same_or_child_path(r"C:\Windows\System32", r"C:\Windows"))
        self.assertTrue(is_same_or_child_path(r"C:\Program Files\App", r"C:\Program Files"))
        self.assertFalse(is_same_or_child_path(r"C:\WindowsArt", r"C:\Windows"))
        self.assertFalse(is_same_or_child_path(r"C:\Program Files Backup", r"C:\Program Files"))


class ConfigValidationTests(unittest.TestCase):
    def test_bool_is_rejected_for_numeric_config_field(self) -> None:
        file_handle, config_path = tempfile.mkstemp(suffix=".json")
        os.close(file_handle)
        try:
            with open(config_path, "w", encoding="utf-8") as config_file:
                json.dump({"download_timeout": True}, config_file)

            config = ScraperConfig.load(config_path)
            self.assertEqual(config.download_timeout, ScraperConfig().download_timeout)
            self.assertIsInstance(config.download_timeout, int)
        finally:
            os.remove(config_path)

    def test_matching_numeric_type_is_still_applied(self) -> None:
        file_handle, config_path = tempfile.mkstemp(suffix=".json")
        os.close(file_handle)
        try:
            with open(config_path, "w", encoding="utf-8") as config_file:
                json.dump({"download_timeout": 25}, config_file)

            config = ScraperConfig.load(config_path)
            self.assertEqual(config.download_timeout, 25)
        finally:
            os.remove(config_path)

class HistorySanitizationTests(unittest.TestCase):
    def test_sanitize_history_url_strips_query_and_fragment(self) -> None:
        self.assertEqual(
            sanitize_history_url("https://example.com/path/image?id=123#section"),
            "https://example.com/path/image",
        )

    def test_sanitize_history_item_text_rewrites_legacy_history_entry(self) -> None:
        original_entry = (
            "2026-03-14 10:00:00 - "
            "https://example.com/path/image?id=123#section (2 images)"
        )
        self.assertEqual(
            sanitize_history_item_text(original_entry),
            "2026-03-14 10:00:00 - https://example.com/path/image (2 images)",
        )


class EnvironmentStatusTests(unittest.TestCase):
    def test_normalize_package_name_matches_pip_style(self) -> None:
        self.assertEqual(normalize_package_name("PyQt5"), "pyqt5")
        self.assertEqual(normalize_package_name("webdriver_manager"), "webdriver-manager")
        self.assertEqual(normalize_package_name("urllib3[socks]"), "urllib3")

    def test_parse_locked_requirements_ignores_comments(self) -> None:
        file_handle, requirements_path = tempfile.mkstemp(suffix=".txt")
        os.close(file_handle)
        try:
            with open(requirements_path, "w", encoding="utf-8") as requirements_file:
                requirements_file.write(
                    "# generated by pip-compile\n"
                    "beautifulsoup4==4.14.3\n"
                    "    # via -r requirements.in\n"
                    "\n"
                    "webdriver-manager==4.0.2\n"
                )

            self.assertEqual(
                parse_locked_requirements(requirements_path),
                {
                    "beautifulsoup4": "4.14.3",
                    "webdriver-manager": "4.0.2",
                },
            )
        finally:
            os.remove(requirements_path)

    def test_build_environment_status_reports_missing_and_mismatched(self) -> None:
        status = build_environment_status(
            {
                "beautifulsoup4": "4.14.3",
                "requests": "2.32.5",
                "selenium": "4.41.0",
            },
            {
                "beautifulsoup4": "4.14.3",
                "requests": "2.31.0",
            },
        )

        self.assertFalse(status.is_in_sync)
        self.assertEqual(status.matching_count, 1)
        self.assertEqual(status.missing, [("selenium", "4.41.0")])
        self.assertEqual(status.mismatched, [("requests", "2.32.5", "2.31.0")])
        self.assertEqual(
            format_environment_status_lines(status),
            [
                "Environment drift detected: 1 missing, 1 mismatched.",
                "Missing: selenium==4.41.0",
                "Mismatched: requests expected 2.32.5, installed 2.31.0",
            ],
        )


class ScraperThreadCancellationTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.qt_app = QCoreApplication.instance() or QCoreApplication([])

    def test_operation_cancelled_error_emits_cancelled_signal(self) -> None:
        thread = ScraperThread("https://example.com", ScraperConfig())
        cancelled_messages = []
        finished_counts = []
        errors = []

        thread.signals.cancelled.connect(cancelled_messages.append)
        thread.signals.finished.connect(finished_counts.append)
        thread.signals.error.connect(errors.append)

        with patch("gui.scrape_images", side_effect=OperationCancelledError("cancelled")):
            thread.run()

        self.assertEqual(cancelled_messages, ["Scraping cancelled."])
        self.assertEqual(finished_counts, [])
        self.assertEqual(errors, [])

    def test_cancel_requested_after_return_still_emits_cancelled_signal(self) -> None:
        thread = ScraperThread("https://example.com", ScraperConfig())
        cancelled_messages = []
        finished_counts = []

        thread.signals.cancelled.connect(cancelled_messages.append)
        thread.signals.finished.connect(finished_counts.append)

        thread.request_cancel()
        with patch("gui.scrape_images", return_value=3):
            thread.run()

        self.assertEqual(cancelled_messages, ["Scraping cancelled."])
        self.assertEqual(finished_counts, [])


class DownloadLimitTests(unittest.TestCase):
    class FakeResponse:
        def __init__(self, chunks, headers):
            self._chunks = chunks
            self.headers = headers

        def raise_for_status(self) -> None:
            return None

        def iter_content(self, chunk_size=8192):
            return iter(self._chunks)

        def __enter__(self):
            return self

        def __exit__(self, exc_type, exc, tb):
            return False

    class FakeSession:
        def __init__(self, response):
            self.response = response
            self.last_kwargs = None

        def get(self, url, **kwargs):
            self.last_kwargs = kwargs
            return self.response

    class FakeSessionContext:
        def __init__(self, session):
            self.session = session

        def __enter__(self):
            return self.session

        def __exit__(self, exc_type, exc, tb):
            return False

    class FakeManager:
        def __init__(self, session):
            self.session = session

        def get_session(self):
            return DownloadLimitTests.FakeSessionContext(self.session)

    def test_download_images_streams_and_removes_oversized_partial_file(self) -> None:
        response = self.FakeResponse(
            chunks=[b"1234", b"56"],
            headers={"content-type": "image/jpeg"},
        )
        session = self.FakeSession(response)
        manager = self.FakeManager(session)
        config = ScraperConfig(min_image_size=1, max_download_size=5)

        with tempfile.TemporaryDirectory() as artist_dir:
            count = download_images(
                {"https://example.com/image.jpg"},
                artist_dir,
                "artwork",
                config,
                manager,
            )

            self.assertEqual(count, 0)
            self.assertTrue(session.last_kwargs["stream"])
            self.assertEqual(os.listdir(artist_dir), [])


if __name__ == "__main__":
    unittest.main()
